### ISSUE TITLE
License mismatch in package.xml and source files for tlsf_cpp

### ISSUE THREAD

**Issue by jaisontj** [ros2/realtime_support#106]
## Bug report
The [package.xml](https://github.com/ros2/realtime_support/blob/master/tlsf_cpp/package.xml#L8) states `GNU Lesser Public License 2.1` whereas, the source files (https://github.com/ros2/realtime_support/blob/master/tlsf_cpp/include/tlsf_cpp/tlsf.hpp#L3) state `Apache License, Version 2.0`

**Comment by clalancette** [comment]
It's not so clear-cut.  `tlsf_cpp` uses `tlsf` under the hood, and `tlsf` is LGPL.  My limited understanding is that combining LGPL and Apache 2.0 license will result in an LGPL package; see https://www.gnu.org/licenses/license-compatibility.html for one interpretation that supports this.  From that perspective, then, `tlsf_cpp` seems to be licensed appropriately.

**Comment by tfoote** [comment]
A package can have multiple licenses and list them in the package.xml
https://www.ros.org/reps/rep-0140.html#license-multiple-but-at-least-one

The most restrictive license is usually the most important but knowing that there are parts under different licenses can be valuable. The more restrictive license on one or more components doesn't change the license on the other components, but does effect the useage of the whole product. The clarity can be especially valuable if the license restrictions are not strictly a superset.

**Comment by clalancette** [comment]
Yeah, I guess the right thing to do is to also list Apachev2 in the package.xml.  I'll go ahead and open a PR to do that.
