### ISSUE TITLE
Test failing on Ubuntu 16.04 with Connext

### ISSUE THREAD

**Issue by jacobperron** [ros2/realtime_support#69]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - source
- Version or commit hash:
  - 0.6.0
- DDS implementation:
  - RTI Connext
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Build and run tests (with Connext installed):

        colcon build --packages-up-to tlsf_cpp
        colcon test --packages-select tlsf_cpp
    
#### Expected behavior

Builds and tests pass.

#### Actual behavior

Builds, but one of the tests fails:

```sh
$ colcon test-result --verbose
build/tlsf_cpp/test_results/tlsf_cpp/test_tlsf__rmw_connext_cpp.gtest.xml: 3 tests, 0 errors, 1 failure, 0 skipped
- tlsf_cpp.AllocatorTest__rmw_connext_cpp allocator_shared_ptr
  <<< failure message
    /root/ros2_ws/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp:370
    Value of: fail
      Actual: true
    Expected: false
  >>>
```

**Comment by clalancette** [comment]
This is pretty far out-of-date, so I'm going to close this.  If we run into a similar issue in the future, we can open a new one.
