### ISSUE TITLE
Is 8GB dynamic memory a hard requirement in rttest?

### ISSUE THREAD

**Issue by r7vme** [ros2/realtime_support#87]
## Bug report

[RT tutorial for ROS2](https://index.ros.org/doc/ros2/Tutorials/Real-Time-Programming/#run-the-tests) mentions that pendulum demo requires 8GB of ram, but does not reasons why. After playing around with rttest i finally was able to understand why it allocates 8GB (see [answer](https://answers.ros.org/question/337066/why-rttest-allocates-8gb-of-memory/?answer=338382#post-id-338382)), but it's still not clear where this prefault logic comes from and it seems 8GB are just accidentally there.

Is it possible to make memory requirement configurable or document/reason approach used in `lock_and_prefault_dynamic`?

Thanks

**Required Info:**

- Operating System:
  - Ubuntu 18.04 (any linux)
- Installation type:
  - rttest compiled by in istructions in [README.md](https://github.com/ros2/realtime_support/tree/a9534f8638d58d38c57a26fa9a97642e642d3662/rttest#build-instructions)
- Version or commit hash:
  - https://github.com/ros2/realtime_support/tree/a9534f8638d58d38c57a26fa9a97642e642d3662
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
```
./example_loop -i 10000
```
In other console open e.g. `top` to check that RES memory is ~8GB.

#### Expected behavior
I want to avoid hard requirement of 8+GB of RAM, so i expect this can be configurable for example.
As alternative documentation can justify 8GB memory requirement.

#### Actual behavior
App requires 8GB RAM, which many boards don't have.

#### Additional information

- [Question](https://answers.ros.org/question/337066/why-rttest-allocates-8gb-of-memory) with answer that describes why 8GB 
- [Blog post](https://www.96boards.org/blog/hikey970-ros2/) which mentions on how to decrease RAM usage.

**Comment by clalancette** [comment]
> I want to avoid hard requirement of 8+GB of RAM, so i expect this can be configurable for example.
> As alternative documentation can justify 8GB memory requirement.

I think it makes sense to make the amount of memory to fault in configurable.  Please consider submitting a PR to make `lock_and_prefault_dynamic()` take an amount of memory to prefault.  I'd be happy to review and merge it.

**Comment by r7vme** [comment]
@clalancette PTAL, i finally had a time to make a PR https://github.com/ros2/realtime_support/pull/89
