### ISSUE TITLE
Standard deviation value is wrong (overflow may happen)

### ISSUE THREAD

**Issue by y-okumura-isp** [ros2/realtime_support#95]
Now I'm testing #94, I find this issue.

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04 (64 bit)
- Installation type:
  - build Eloquent
  - master also has this problem
- DDS implementation:
  - unrelated
- Client library (if applicable):
  - rttest

#### Steps to reproduce issue
- run example_loop, and we get following stdout.

```
# ./example_loop -d 1gb -s rr -i 10000 -f out.txt
Writing results to file: out.txt
Initial major pagefaults: 0
Initial minor pagefaults: 262500
rttest statistics for new.txt:
  - Minor pagefaults: 0
  - Major pagefaults: 0
  Latency (time after deadline was missed):
    - Min: 9792 ns
    - Max: 570881 ns
    - Mean: 82055.158300 ns
    - Standard deviation: 141.661569
```

- If you run many times, you'll get large standard deviation such as 42949672.959047.

- Anyway, run following to calcurate true standard deviation.
  Different values are returned.

```
# run in ipython session
import numpy as np
np.loadtxt("out.txt", skiprows=1)[:, 2].std()
# 10,000 order value is returned, for example 27376.849010133381
```

- I think overflow happens.

#### Expected behavior
see above

#### Actual behavior
see above

#### Additional information
To calcurate standard deviation, Rttest::calculate_statistics does following (I wrote python-numpy like formula after "i.e.".)
- (1) minus mean i.e. `x = x - x.mean()` where x is jitter vector.
- (2) get inner product i.e. `x = np.dot(x, x)`
- (3) divide by N and sqrt i.e. `x = math.sqrt(x/N)`

To reduce the possibility of overflow, I propose to divide by sqrt(N) first.
- (1) minus mean i.e. `x = x - x.mean()`
- (2) divide by sqrt(N) i.e. `x = x / sqrt(N)`
- (3) get inner product i.e. `x = np.dot(x, x)`
- (4) we already divide, so only take sqrt i.e. `x = math.sqrt(x)`

Here is my workaround code(I get almost same output as numpy).
If OK, I'll send PR.

```
// Rttest::calculate_statistics in rttest.cpp
// https://github.com/ros2/realtime_support/blob/master/rttest/src/rttest.cpp#L839

// before
  std::vector<int64_t> latency_diff(latency_dataset.size());
  std::transform(
    latency_dataset.begin(), latency_dataset.end(), latency_diff.begin(),
    std::bind(std::minus<int>(), std::placeholders::_1, output->mean_latency));
  int64_t sq_sum = std::inner_product(
    latency_diff.begin(), latency_diff.end(), latency_diff.begin(), 0);
  output->latency_stddev = std::sqrt(sq_sum / latency_dataset.size());


// after
   std::transform(
     latency_dataset.begin(), latency_dataset.end(), latency_diff.begin(),
     std::bind(std::minus<int>(), std::placeholders::_1, output->mean_latency));
  // forst divide by sqrt(n)
  auto n = latency_dataset.size();
  std::vector<double> latency_div(n);
  std::transform(
	  latency_diff.begin(), latency_diff.end(), latency_div.begin(),
	  [n](int64_t x) -> double { return x / std::sqrt(n); });
  // inner_product
   int64_t sq_sum = std::inner_product(
     latency_div.begin(), latency_div.end(), latency_div.begin(), 0);
   output->latency_stddev = std::sqrt(sq_sum);
```

**Comment by clalancette** [comment]
This looks fine, yes.  Please make sure to put this change in a separate PR from what you are working on in #94; it will make them both easier to review.
